# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install global dependencies
RUN npm install -g npm@latest esbuild

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install root dependencies
RUN npm install --ignore-scripts

# Copy the rest of the repository
COPY . .

# Install mcp-server dependencies
RUN npm install --prefix mcp-server --ignore-scripts

# Build the project (both mcp-server and firefox-extension, now that esbuild is available)
RUN npm run build

# Start the MCP server
CMD [ "node", "mcp-server/dist/server.js" ]
